import json
import random
########################################################################

# Do not modify the lines above

########################################################################

# You can add any import statements from inbuilt libraries here
import math



########################################################################

# Do not install any more external packages. You can only use Python's default libraries such as:
# json, math, itertools, collections, functools, random, heapq, etc.

########################################################################

def normalize(array):
    total = sum(array)
    return [x / total for x in array] if total > 0 else array

generator1=0o5
generator2=0o7

def _xor_from_generator(reg, generator):
    """
    Compute XOR of register bits with generator polynomial.
    - reg: [oldest ... newest]
    - generator: integer, e.g. 0o5 -> 0b101
    """
    val = 0
    for i, b in enumerate(reg):
        if (generator >> i) & 1:
            val ^= b
    return val

def generate_trellis(generator1, generator2, history_length=3):
    """
    RSC trellis matching tester.encoder():
      - shift in u
      - compute feedback from (u + previous state) via generator2
      - replace newest with feedback
      - parity from generator1 on modified register
      - next_state are the last (K-1) bits after feedback
    """
    K = history_length
    m = K - 1
    num_states = 1 << m
    mask = (1 << m) - 1
    trans = {s: {} for s in range(num_states)}

    for s in range(num_states):
        reg_prefix = [(s >> i) & 1 for i in reversed(range(m))]

        for u in (0, 1):
            reg = reg_prefix + [u]
            fb = _xor_from_generator(reg, generator2)
            reg_mod = reg[:-1] + [fb]
            p = _xor_from_generator(reg_mod, generator1)
            next_state = 0
            for bit in reg_mod[1:]:
                next_state = (next_state << 1) | bit
            next_state &= mask

            trans[s][u] = (next_state, p)

    return {"num_states": num_states, "trans": trans,
            "start_state": 0, "end_state": 0}

def viterbi(systematic, parity, probability_matrix, trellis=None):
    """
    Viterbi decoder for a single convolutional encoder branch.
    - systematic: list of observed levels for the systematic channel (length T)
    - parity: list of observed levels for the parity channel (length T)
    - probability_matrix: [P(level|bit=0), P(level|bit=1)] (each is a list over levels)
    - trellis: generated by generate_trellis; if None, uses global generators with history_length=3.
    Returns decoded bitstring (e.g., '01010...')
    """
    if trellis is None:
        trellis = generate_trellis(generator1, generator2, history_length=3)
    T = len(systematic)
    S = trellis["num_states"]
    trans = trellis["trans"]
    start_state = trellis["start_state"]

    LOGZERO = -1e9
    def safe_log(x):
        if x <= 0:
            return LOGZERO
        return math.log(x)

    prev_scores = [LOGZERO] * S
    prev_scores[start_state] = 0.0
    backptr = [ [None]*S for _ in range(T) ]

    for t in range(T):
        sys_obs = systematic[t]
        par_obs = parity[t]
        cur_scores = [LOGZERO] * S
        cur_backptr = [None] * S
        for s in range(S):
            if prev_scores[s] <= LOGZERO:
                continue
            for u in (0,1):
                ns, p = trans[s][u]
                emis = probability_matrix[u][sys_obs] * probability_matrix[p][par_obs]
                if emis <= 0:
                    score = LOGZERO
                else:
                    score = prev_scores[s] + safe_log(emis)
                if score > cur_scores[ns]:
                    cur_scores[ns] = score
                    cur_backptr[ns] = (s, u)
        prev_scores = cur_scores
        backptr[t] = cur_backptr

    final_state = max(range(S), key=lambda s: prev_scores[s])
    bits = [0] * T
    s = final_state
    for t in reversed(range(T)):
        entry = backptr[t][s]
        if entry is None:
            bits[t] = 0
            s = trellis["start_state"]
        else:
            prev_s, bit = entry
            bits[t] = bit
            s = prev_s
    return ''.join(str(b) for b in bits)

def bcjr(systematic, parity, probability_matrix, app_probability=None, trellis=None):
    """
    BCJR (forward-backward) decoder for a single convolutional encoder branch.
    - systematic: list of observed levels for systematic channel (length T)
    - parity: list of observed parity levels (length T)
    - probability_matrix: [P(level|bit=0), P(level|bit=1)]
    - app_probability: prior on bits as shape (2, T) -> [ [P(bit=0)_t], [P(bit=1)_t] ]
                       If None, uniform prior is assumed.
    - trellis: generated trellis; if None, uses defaults.
    Returns posterior probabilities as [post0_list, post1_list] each length T.
    """
    if trellis is None:
        trellis = generate_trellis(generator1, generator2, history_length=3)
    T = len(systematic)
    S = trellis["num_states"]
    trans = trellis["trans"]
    start_state = trellis["start_state"]
    end_state = trellis["end_state"]

    eps = 1e-12
    if app_probability is None:
        app0 = [0.5]*T
        app1 = [0.5]*T
    else:
        app0 = list(app_probability[0])
        app1 = list(app_probability[1])

    gamma = [ [ {0:0.0, 1:0.0} for _ in range(S) ] for _ in range(T) ]
    for t in range(T):
        sys_obs = systematic[t]
        par_obs = parity[t]
        for s in range(S):
            for u in (0,1):
                ns, p = trans[s][u]
                emis = probability_matrix[u][sys_obs] * probability_matrix[p][par_obs]
                prior_u = app0[t] if u==0 else app1[t]
                gamma[t][s][u] = emis * max(prior_u, eps)

    # Forward (alpha)
    alpha = [ [0.0]*S for _ in range(T+1) ]
    alpha[0][start_state] = 1.0
    for t in range(T):
        for s in range(S):
            a_s = alpha[t][s]
            if a_s == 0.0:
                continue
            for u in (0,1):
                ns = trans[s][u][0]
                contrib = a_s * gamma[t][s][u]
                alpha[t+1][ns] += contrib
        ssum = sum(alpha[t+1])
        if ssum > 0:
            alpha[t+1] = [x/ssum for x in alpha[t+1]]

    # Backward (beta)
    beta = [ [0.0]*S for _ in range(T+1) ]
    beta[T][end_state] = 1.0
    for t in reversed(range(T)):
        for s in range(S):
            val = 0.0
            for u in (0,1):
                ns = trans[s][u][0]
                val += gamma[t][s][u] * beta[t+1][ns]
            beta[t][s] = val
        ssum = sum(beta[t])
        if ssum > 0:
            beta[t] = [x/ssum for x in beta[t]]

    post0 = [0.0]*T
    post1 = [0.0]*T
    for t in range(T):
        numer0 = 0.0
        numer1 = 0.0
        for s in range(S):
            for u in (0,1):
                ns = trans[s][u][0]
                contrib = alpha[t][s] * gamma[t][s][u] * beta[t+1][ns]
                if u == 0:
                    numer0 += contrib
                else:
                    numer1 += contrib
        ssum = numer0 + numer1
        if ssum <= 0:
            post0[t] = app0[t]
            post1[t] = app1[t]
        else:
            post0[t] = numer0/ssum
            post1[t] = numer1/ssum
    return [post0, post1]
    
class Inference:
    def __init__(self, testcase):
        ### NOTE that you will not have access to the original bitstring in the actual evaluation
        self.noisy_output = testcase["noisy_output"]
        self.length = len(self.noisy_output)//3
        self.probability_matrix = testcase["probability_matrix"]
        self.probability_matrix = [normalize(self.probability_matrix), normalize(self.probability_matrix)[::-1]]
        self.permutation = testcase["permutation"]
        
        # split noisy_output into three streams: systematic, parity1, parity2
        T = self.length
        arr = self.noisy_output
        self.sys = [ arr[3*i] for i in range(T) ]
        self.p1  = [ arr[3*i+1] for i in range(T) ]
        self.p2  = [ arr[3*i+2] for i in range(T) ]

        # build permuted systematics -> sys_perm[t] = systematic bit observed that encoder2 saw at time t
        self.sys_perm = [ self.sys[self.permutation[k]] for k in range(T) ]

        self.inv_permutation = [0]*T
        for t in range(T):
            self.inv_permutation[self.permutation[t]] = t

        self.trellis = generate_trellis(generator1, generator2, history_length=3)

    def get_viterbi_output(self):
        bits = viterbi(self.sys, self.p1, self.probability_matrix, trellis=self.trellis)
        return bits

    def get_bcjr_output(self):
        post = bcjr(self.sys, self.p1, self.probability_matrix, app_probability=None, trellis=self.trellis)
        bits = ''.join('0' if post[0][i] >= post[1][i] else '1' for i in range(self.length))
        return bits

    def get_turbocode_output(self):
        # def get_turbocode_output(self, iterations=8, delta=1e-3):
        iterations=8
        delta=1e-3
        T = self.length
        apriori = [[0.5]*T, [0.5]*T]
        iters_used = iterations

        for it in range(iterations):
            old_apriori = [apriori[0][:], apriori[1][:]]

            # Decoder 1 (original order)
            post1 = bcjr(self.sys, self.p1, self.probability_matrix, app_probability=apriori, trellis=self.trellis)

            # extrinsic from decoder 1: post / apriori, normalized per time
            ext1 = [[0.0]*T, [0.0]*T]
            for t in range(T):
                a0 = max(apriori[0][t], 1e-12)
                a1 = max(apriori[1][t], 1e-12)
                e0 = post1[0][t] / a0
                e1 = post1[1][t] / a1
                s  = e0 + e1
                if s <= 0:
                    ext1[0][t] = 0.5; ext1[1][t] = 0.5
                else:
                    ext1[0][t] = e0/s; ext1[1][t] = e1/s

            # interleave extrinsic -> apriori for decoder 2 (permuted time)
            apriori2 = [
                [ ext1[0][ self.permutation[t] ] for t in range(T) ],
                [ ext1[1][ self.permutation[t] ] for t in range(T) ],
            ]

            # Decoder 2 (permuted order)
            post2 = bcjr(self.sys_perm, self.p2, self.probability_matrix,
                        app_probability=apriori2, trellis=self.trellis)

            # extrinsic from decoder 2 in permuted time
            ext2_perm = [[0.0]*T, [0.0]*T]
            for t in range(T):
                a0 = max(apriori2[0][t], 1e-12)
                a1 = max(apriori2[1][t], 1e-12)
                e0 = post2[0][t] / a0
                e1 = post2[1][t] / a1
                s  = e0 + e1
                if s <= 0:
                    ext2_perm[0][t] = 0.5; ext2_perm[1][t] = 0.5
                else:
                    ext2_perm[0][t] = e0/s; ext2_perm[1][t] = e1/s

            # extrinsic back to original with inv_perm
            new_apriori0 = [ ext2_perm[0][ self.inv_permutation[i] ] for i in range(T) ]
            new_apriori1 = [ ext2_perm[1][ self.inv_permutation[i] ] for i in range(T) ]
            apriori = [new_apriori0, new_apriori1]

            # convergence check
            max_change = max(abs(apriori[1][t] - old_apriori[1][t]) for t in range(T))
            if max_change < delta:
                iters_used = it + 1
                # print(f"Stopping criterion reached after {iters_used} iterations.")
                break

        # average posteriors
        post2_deint0 = [ post2[0][ self.inv_permutation[i] ] for i in range(T) ]
        post2_deint1 = [ post2[1][ self.inv_permutation[i] ] for i in range(T) ]

        final0 = [(post1[0][t] + post2_deint0[t]) / 2.0 for t in range(T)]
        final1 = [(post1[1][t] + post2_deint1[t]) / 2.0 for t in range(T)]

        return ''.join('0' if final0[t] >= final1[t] else '1' for t in range(T))

if __name__ == "__main__":
    with open("turbocodes_testcases.json", "r") as f:
        data = json.load(f)

    testcases = data["testcases"]

    results = []

    for i, testcase in enumerate(testcases, start=1):
        infer = Inference(testcase)

        viterbi_out = infer.get_viterbi_output()
        bcjr_out = infer.get_bcjr_output()
        turbo_out = infer.get_turbocode_output()
        results.append({
            "testcase": i,
            "viterbi_errors": len([j for j in range(len(viterbi_out)) if viterbi_out[j] != testcase["bitstring"][j]]),
            "bcjr_errors": len([j for j in range(len(bcjr_out)) if bcjr_out[j] != testcase["bitstring"][j]]),
            "turbo_errors": len([j for j in range(len(turbo_out)) if turbo_out[j] != testcase["bitstring"][j]]),
        })

    with open("turbocodes_results.json", "w") as f:
        json.dump(results, f, indent=4)